webShopPrototypeDjango/ShopPrototype/ShopPrototype/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webShopPrototypeDjango/ShopPrototype/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('basket', views.basket, name='basket'),
    path('order', views.order_page, name='order'),
    path('thanks_page', views.thanks_page, name='thanks_page'),
    path('buy', views.buy, name='buy'),
    path('delete', views.delete, name='delete'),
    path('update_cart', views.update_data_cart, name='update_cart')
]

webShopPrototypeDjango/ShopPrototype/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ProductsView.as_view()),
    path('catalog', views.ProductsView.as_view()),
    path('about_us', views.about_us),
    path('contacts', views.contacts),
    path('filter/', views.FilterProductsView.as_view(), name='filter'),
    path('add_to_cart/', views.DetailProductView.as_view(), name='add_to_cart'),
    path('<slug:slug>', views.DetailProductView.as_view(), name='product_detail')
]

webShopPrototypeDjango/ShopPrototype/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('register', views.RegisterView.as_view(), name='register')
]

webShopPrototypeDjango/ShopPrototype/cart/models.py
from django.db import models
from main.models import Product


class Orders(models.Model):
    STATE_CHOICES = (
        ('NotProcessed', 'Not Processed'),
        ('InProgress', 'InProgress'),
        ('Processed', 'Processed'),
    )
    user_name = models.CharField('Name', max_length=100)
    user_surname = models.CharField('Surname', max_length=100)
    email = models.EmailField('Email')
    number_phone = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    house_number = models.CharField(max_length=50)
    street = models.CharField(max_length=100)
    product = models.ManyToManyField(Product, through='OrderItem')
    state = models.CharField('State', max_length=20, choices=STATE_CHOICES, default='NotProcessed')


class OrderItem(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantity product')

webShopPrototypeDjango/ShopPrototype/main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField('Category', max_length=150)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    title = models.CharField('Product', max_length=150)
    photo = models.ImageField('Photo of product', upload_to='products/')
    description = models.TextField('Description')
    category = models.ForeignKey(Category, verbose_name='Category', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField('Price', max_digits=10, decimal_places=2)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Draft', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

webShopPrototypeDjango/ShopPrototype/users/models.py
from django.db import models

webShopPrototypeDjango/ShopPrototype/users/forms.py
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

webShopPrototypeDjango/ShopPrototype/cart/views.py
from django.shortcuts import render, redirect
from main.models import Product
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
from .models import Orders, OrderItem
from .cart import Cart


def basket(request):
    data_cart = request.session['cart']
    product_ids = set(data_cart.keys())
    products = Product.objects.filter(id__in=product_ids)
    cart_items = []
    total_price = 0
    for key, value in data_cart.items():
        product = products.get(id=key)
        cart_item = {
            'product': product,
            'quantity': value,
        }

        price = product.price * value
        total_price += price

        cart_items.append(cart_item)

    context = {'cart_items': cart_items, 'total_price': total_price}
    return render(request, 'cart/basket.html', context)


def delete(request):
    product_id = request.POST.get('product_id')
    cart = Cart(request)
    cart.delete_product_in_cart(product_id)
    return redirect('cart:basket')


@csrf_exempt
def update_data_cart(request):
    cart = Cart(request)
    if request.method == 'POST':
        data = request.body.decode('utf-8')
        dictionary = json.loads(data)
        cart.upgrade_product_in_cart(dictionary)
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})


def order_page(request):
    return render(request, 'cart/order.html')


def buy(request):
    data_cart = request.session['cart']
    product_ids = set(data_cart.keys())
    products = Product.objects.filter(id__in=product_ids)
    print(data_cart)
    orders = Orders.objects.create(
        user_name=request.POST.get('user_name'),
        user_surname=request.POST.get('user_surname'),
        email=request.POST.get('email'),
        number_phone=request.POST.get('number_phone'),
        city=request.POST.get('city'),
        house_number=request.POST.get('house_number'),
        street=request.POST.get('street'),
    )
    for product in products:
        print(product.id)
        OrderItem.objects.create(order=orders, product=product, quantity=data_cart[str(product.id)])
    Cart(request).empty_trash()
    return redirect('cart:thanks_page')


def thanks_page(request):
    return render(request, 'cart/thanksgiving.html')

webShopPrototypeDjango/ShopPrototype/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Product, Category
from cart.cart import Cart


class CategoryList:

    def get_category(self):
        return Category.objects.all()


class ProductsView(CategoryList, ListView):
    model = Product
    queryset = Product.objects.filter(draft=False)
    template_name = 'main/product_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        context['cart'] = cart
        return context


class DetailProductView(CategoryList, DetailView):
    model = Product
    slug_field = "url"

    def post(self, request, *args, **kwargs):
        product_id = request.POST.get('product_id')
        cart = Cart(request)
        cart.add_product_in_cart(product_id)
        return redirect('cart:basket')


class FilterProductsView(CategoryList, ListView):
    def get_queryset(self):
        queryset = Product.objects.filter(category__in=self.request.GET.getlist("category"))
        return queryset


def about_us(request):
    return render(request, 'main/about_us.html')


def contacts(request):
    return render(request, 'main/contacts.html')

webShopPrototypeDjango/ShopPrototype/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView
from cart.models import Orders
from .forms import RegisterForm


@login_required()
def profile(request):
    email = request.user.email
    user = User.objects.get(email=email)
    is_admin = user.is_staff
    orders = Orders.objects.filter(email=email).prefetch_related('orderitem_set__product')
    context = {'orders': orders, 'is_admin': is_admin}
    return render(request, 'users/profile.html', context)


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy("users:profile")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

webShopPrototypeDjango/ShopPrototype/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/users/css/main.css">
    <title>ShopPrototype</title>
</head>
<body>
    <div class="header">
      <a href="/"><span class="logo">Shop Prototype</span></a>
      <nav>
        <a href="/catalog">Catalog</a>
        <a href="/contacts">Contacts</a>
        <a href="/about_us">About Us</a>
        <a href="/cart/basket"><img src="../../static/main/img/shopping_cart_icon.svg" alt="Shopping Cart"></a> <!-- Значок корзины -->
        <a href="/users/profile"><img src="../../static/main/img/profile.svg" alt="Profile"></a> <!-- Значок профиля -->
          {% if is_admin %}
        <a href="/admin">Admin Panel</a> <!-- Ссылка на админ-панель -->
        {% endif %}
        <a><button type="submit" class="exit" onclick="location.href='{% url 'logout' %}?next=/users/profile'">Exit</button></a>
      </nav>
    </div>

    <div class="profile-wrap">
        <div class="profile">
            <div class="profile-container">
                <div class="profile__nickname">
                    <h2>Nickname:</h2>
                    {{ user.username }}
                </div>
                <div class="profile__phone">
                    <h2>Email:</h2>
                    {{ user.email }}
                </div>
            </div>
        </div>
        <div class="history">
            <h2>Order history:</h2>
            <div class="history__wrap">
                {% for order in orders %}
                <div class="history__item" data-product-price="{{ order_item.product.price }}">
                    {% for order_item in order.orderitem_set.all %}
                    <img src="{{ order_item.product.photo.url }}" alt="{{ order_item.product.name }}">
                    <h3 class="history__title">
                        <h4>Name:</h4>
                        {{ order_item.product.name }}
                    </h3>
                    <div class="history__amount">
                        <h4>Amount:</h4>
                        {{ order_item.quantity }}
                    </div>
                    <div class="history__total-price">
                        <h4>Price:</h4>
                        <span class="total-price"></span>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script src="../../static/users/js/total_price.js"></script>
</body>
</html>